Quick script to generate data for Choosing policy page
isimluk/openscap-portal pull request #202
Opened 2021-01-25 09:34 UTC by jan-cerny

Usage example:
./choosing_policy_page.py ~/work/git/scap-security-guide/
Copy paste the output of this script to
https://www.open-scap.org/security-policies/choosing-policy/
between

and

2021-01-25 09:34 UTC, pep8speaks commented
Hello @jan-cerny! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`utils/choosing_policy_page.py`](https://github.com/OpenSCAP/website/blob/ccc5000f14dad0feb7bed1545d37781f34597b25/utils/choosing_policy_page.py):

> [Line 14:1](https://github.com/OpenSCAP/website/blob/ccc5000f14dad0feb7bed1545d37781f34597b25/utils/choosing_policy_page.py#L14): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 35:80](https://github.com/OpenSCAP/website/blob/ccc5000f14dad0feb7bed1545d37781f34597b25/utils/choosing_policy_page.py#L35): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (159 > 79 characters)
> [Line 44:33](https://github.com/OpenSCAP/website/blob/ccc5000f14dad0feb7bed1545d37781f34597b25/utils/choosing_policy_page.py#L44): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2021-01-25 11:04 UTC, matejak requested changes
It looks good, I would just suggest to split the function into one that gathers data, and another one that outputs the HTML.

I would even consider harnessing Jinja2, as you can specify the template even as a string in the file, and then just render it. That would make it easy to adjust the HTML code if there is ever need. However, that is just up to you if you like that proposal, it's not a merge blocker.

2021-06-15 07:23 UTC, jan-cerny commented
@matejak Is it OK now?

2021-07-27 15:31 UTC, matejak approved these changes

2021-07-27 15:32 UTC, matejak commented
Yes, thanks!

2021-07-27 15:32 UTC, merged